### PR TITLE
[MERTL-141] Update jquery-ui to 1.13.1

### PR DESCRIPTION
**Pull request by pedro-lb**
# PR Description

This PR updates the `jquery-ui` version to 1.13.1, alongside the gem version to `6.0.2`.

The files were gathered from https://github.com/jquery/jquery-ui @ [e21a2543b55680f23aaa7efa38f3288b8e767e7d](https://github.com/jquery/jquery-ui/commit/e21a2543b55680f23aaa7efa38f3288b8e767e7d).

### CODE REVIEW

**Review by lws803 — CHANGES_REQUESTED** [review]
Hmm I've tried to install this specific branch to my local env but ran into some issues on precompiling the webapp :x

steps to reproduce:
1. Install updated version of `jquery-ui-rails`:
```ruby
gem 'jquery-ui-rails',
    git: 'https://github.com/pedro-lb/jquery-ui-rails.git',
    branch: 'mertl-141-update-jquery-ui-version-to-1.13.1'
```
2. Bundle install
3. Clobber existing assets `RAILS_ENV=development rails assets:precompile`
4. Precompile `RAILS_ENV=development rails assets:precompile`

Error:

```
rails aborted!
Sprockets::FileNotFound: couldn't find file 'jquery-ui/jquery-1-7' with type 'application/javascript'
```

**Comment by pedro-lb** [comment]
> Hmm I've tried to install this specific branch to my local env but ran into some issues on precompiling the webapp :x
> 
> steps to reproduce:
> 
> 1. Install updated version of `jquery-ui-rails`:
> 
> ```ruby
> gem 'jquery-ui-rails',
>     git: 'https://github.com/pedro-lb/jquery-ui-rails.git',
>     branch: 'mertl-141-update-jquery-ui-version-to-1.13.1'
> ```
> 
> 2. Bundle install
> 3. Clobber existing assets `RAILS_ENV=development rails assets:precompile`
> 4. Precompile `RAILS_ENV=development rails assets:precompile`
> 
> Error:
> 
> ```
> rails aborted!
> Sprockets::FileNotFound: couldn't find file 'jquery-ui/jquery-1-7' with type 'application/javascript'
> ```

Good catch! Thanks @lws803!

I forgot to update `app/assets/javascripts/jquery-ui.js`. It's now fixed in aa2a23a194ec11608b839118fc3ca4a69eb3a987.

I've tested precompiling assets with this new revision and it works just fine:

```bash
> RAILS_ENV=development bin/rails assets:clobber
> RAILS_ENV=development bin/rails assets:precompile

...

Compiling...
Compiled all packs in /home/pedro/apps/constructor/website/public/packs
```

**Review by lws803 — COMMENTED** [review]
Hmmm this might be intentional, but I still see some `1.12.1` jquery ui modules in `application.js` though, even after updating the bundle, clobbering, precompiling and doing a hard refresh

CleanShot 2022-06-03 at 20 46 47@2x


I do see `1.131` modules as well though 🤔 so I'm fairly confident we're indeed updating the jquery ui modules

**Comment by pedro-lb** [comment]
> Hmmm this might be intentional, but I still see some `1.12.1` jquery ui modules in `application.js` though, even after updating the bundle, clobbering, precompiling and doing a hard refresh
> 
> CleanShot 2022-06-03 at 20 46 47@2x
> 
> I do see `1.131` modules as well though 🤔 so I'm fairly confident we're indeed updating the jquery ui modules

Hmmm, that's curious.

I was able to reproduce this locally and pinpoint the problem to this gem (just as a sanity check) by removing `//= require jquery-ui` from `application.js` and re-bundling the assets - by doing this, there's no `1.12.1` (or `1.13.1`) on those pages.

I'll take a look in-depth today to see what I can find.

**Comment by pedro-lb** [comment]
@lws803 I did some further changes to properly re-generate all assets with `jquery-ui @1.13.1`, using the bundled Rakefile.

When comparing our application bundle at `master` and with this new version, we have a difference as noted below. I think this should be good to go now? The `1.12.1` matches seem to be intentional from `jquery-ui` (I may be wrong here).

## Master

image

## This branch

image

**Comment by lws803** [comment]
> When comparing our application bundle at master and with this new version, we have a difference as noted below. I think this should be good to go now? The 1.12.1 matches seem to be intentional from jquery-ui (I may be wrong here).

Hmmm that's interesting 🤔 afaik all jqueryui packages should be upgraded to `1.13.1`. I might need a second opinion on this from @shagabutdinov as I am not too well-versed with jquery libraries.

**Comment by pedro-lb** [comment]
@lws803 That's correct, looking into it a bit further we can't have any `1.12.1` versions.

It took a bit of time hacking, but I solved this. I think we had some conflicts with the other gem which was also installed locally (`jquery-ui-rails`) when installing it from `git`, so some files were getting mixed when precompiling the assets (since `sprockets` would lookup all installed gems under the name `jquery-ui-rails`).

I solved it by patching the `Rakefile`, re-generating all code for `1.13.1`, updating the gem name and version, and finally republishing it:

- https://rubygems.org/gems/jquery-ui-rails-test

ps. the code above is available at [this branch](https://github.com/pedro-lb/jquery-ui-rails/tree/gem-jquery-ui-rails-test).

Also, by clearing a lot of stuff locally to make sure that things do reflect:

```bash
rm -rf node_modules/.cache ./public/assets ./public/packs ./tmp/cache \
  && bin/rails assets:clean \
  && bin/rails assets:clobber \
  && bin/rails assets:precompile \
  && bin/rails server
```

I'll publish a new version with all fixes (and a better name 😅) under our official account so that we can solve this once and for all! Also, I'll ping you as soon as this is ready for review with new testing instructions.

image

image

**Comment by pedro-lb** [comment]
New gem published at rubygems: [jquery-ui-rails-patch-1131](https://rubygems.org/gems/jquery-ui-rails-patch-1131)

**Comment by pedro-lb** [comment]
Just as a sanity check, new tests using the [new gem](https://rubygems.org/gems/jquery-ui-rails-patch-1131):

image

image

**Comment by pedro-lb** [comment]
@lws803 all done! 

Please check the internal PR for testing instructions.

**Review by lws803 — APPROVED** [review]
LGTM! Tested it on the main webapp branch and everything's working

**Pull request merged**
